//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCIC_Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainArticle
    {
        public int artID { get; set; }
        public string title { get; set; }
        public string desc { get; set; }
        public string imgUrl { get; set; }
        public string imgCaption { get; set; }
        public string author { get; set; }
        public string authorEmail { get; set; }
        public string authorSource { get; set; }
        public Nullable<System.DateTime> postDate { get; set; }
        public Nullable<System.DateTime> archiveDate { get; set; }
        public Nullable<System.DateTime> sortDate { get; set; }
        public Nullable<System.DateTime> pubDate { get; set; }
        public string url { get; set; }
        public string sourceName { get; set; }
        public string sourceUrl { get; set; }
        public string C_type { get; set; }
        public string loe { get; set; }
        public string directorate { get; set; }
        public string cta { get; set; }
        public string promote { get; set; }
        public Nullable<System.DateTime> repostDate { get; set; }
        public string googleTrack { get; set; }
        public string group { get; set; }
        public string connection { get; set; }
        public string initiative { get; set; }


      
    }
}
