//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCIC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngagementCalendar
    {
        public int eventID { get; set; }
        public string title { get; set; }
        public string desc { get; set; }
        public System.DateTime start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string EventUrl { get; set; }
        public byte[] stamp { get; set; }
    }
}
