//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCIC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public int sourceId { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public string logo { get; set; }
        public string type { get; set; }
    }
}
