//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCIC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSPVideo
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string desc { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> postDate { get; set; }
        public string category { get; set; }
        public Nullable<System.DateTime> stamp { get; set; }
    }
}
