//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCIC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int artID { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string desc { get; set; }
        public string pubDate { get; set; }
        public Nullable<System.DateTime> postDate { get; set; }
        public string link { get; set; }
        public string img { get; set; }
        public string group { get; set; }
        public string typ { get; set; }
        public string source { get; set; }
        public string sourceLogo { get; set; }
        public string archive { get; set; }
        public string directorate { get; set; }
        public string connection { get; set; }
        public string lineofeffort { get; set; }
        public string initiative { get; set; }
        public string focus { get; set; }
    }
}
